### ISSUE TITLE
add command for deleting security group

### ISSUE THREAD

**Issue by cricketlong** [OpenTelekomCloud/python-otcclient#10]
There commands for creating and listing security groups, but no for deleting.

**Comment by zsoltn** [comment]
Request accepted in VER 1.1 .  Under implementation.

**Comment by spielkind** [comment]
It should be possible to use multiple security groups for one ECS, these option exists in the API.

**Comment by zsoltn** [comment]
It looks like delete already working. See: 
otc ecs create-security-group --group-name mytest2 --vpc-name myvpc
ecs delete-security-group --group-name mytest2 --vpc-name testvpc
Using  multiple security groups if necessary need other issue. ( discuss separately)
