### ISSUE TITLE
instance security-groups attribute lists vpc id and not security group

### ISSUE THREAD

**Issue by zamiam69** [OpenTelekomCloud/python-otcclient#29]
This is also present in otc-tool and likely an OTC API bug. If you list a specific instance (*describe_instances* with *OtcConfig.INSTANCE_ID* set) the *['server']['security_groups']* attribute contains the vpc id and nothing else.

**Comment by hodigy** [comment]
Issue is still valid, but it's not on CLI side, but API.

**Comment by garloff** [comment]
Hi György,

The issue has been fixed on the API side with the Mitaka update - old VMs do not benefit from it, only new ones though. 

HTH, 
-- 
Kurt Garloff <kurt@garloff.de>
(Sent from Mobile with K9. Please excuse brevity & typos.)

Am 5. März 2017 01:30:10 MEZ schrieb hodigy <notifications@github.com>:

**Comment by hodigy** [comment]
Issue could be closed as it's corrected with Mitaka update.

**Comment by zsoltn** [comment]
Based on prev comments CLOSED.
